#!/bin/bash
docker run -it \
	-v $PWD/src:/app/src \
	-v $PWD/testing:/app/testing \
	-v $PWD/dist:/app/dist \
	-v $PWD/webpack.config.js:/app/webpack.config.js \
	-v $PWD/package.json:/app/package.json \
	-p 8080:80 \
	dtn-client:local /bin/sh